@Starbucks.Api_HostAddress = http://localhost:5100

GET {{ Starbucks.Api_HostAddress}}/api/Category
Accept: application/json

###
POST  {{ Starbucks.Api_HostAddress}}/api/Coffe
Accept: application/json
Content-Type: application/json

{
    "name": "Cafe Argentino",
    "description": "Cafe dulce",
    "price": 50,
    "categoryId" : 1,
    "imagen": ""
}
###
